# Generated by Django 3.2 on 2023-07-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0002_model_assets_model_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model_assets',
            new_name='model_details',
        ),
    ]
