# Generated by Django 3.2 on 2023-07-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0003_rename_model_assets_model_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_details',
            name='Username',
        ),
        migrations.AlterField(
            model_name='model_info',
            name='approx_followers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model_info',
            name='height_feet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
