# Generated by Django 3.2 on 2023-07-22 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Spymain', '0004_auto_20230719_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_details',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='model_info',
            name='profile_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profilephoto/'),
            preserve_default=False,
        ),
    ]
